Refactor dpdk chassis manager
ipdk-io/stratum-dev pull request #21
Opened 2022-10-25 15:23 UTC by ffoulkes

Refactor dpdk_chassis_manager:

- Moved constant definitions to dpdk_port_constants.h.

- Factored out PortConfig class, renamed it to DpdkPortConfig,
  and moved the definition and implementation to separate files.

- Implemented SetParam, SetHotplugParam, and IsParamSet methods
  in DpdkPortConfig.

- Made the configuration bitmask a part of DpdkPortConfig.
  Implemented access methods to replace direct operations on
  the configuration mask.

- Removed PORT_DONE and HOTPLUG_DONE bits from the configuration
  mask and replaced them with port_done and hotplug_done member
  variables.

- Normalized the log messages issued when port parameters are set.

- Implemented a dpdk_port_config unit test.

Remove HotplugConfigParams member from PortConfigParams class:

- The PortConfigParams and HotplugConfigParams structures are
  orthogonal. Embedding one within the other complicates things
  unnecessarily.

Remove unused parameters from DPDK-specific AddPort method:

- Removed the unused speed_bps and fec_mode parameters from the
  DPDK-specific AddPort SDE method. The method now requires only
  device, port, and configuration structure.

- Modified dpdk_sde_wrapper to return ERR_UNIMPLEMENTED if the
  legacy AddPort method is called.

- Modified tofino_sde_wrapper to return ERR_UNIMPLEMENTED if the
  DPDK-specific AddPort method is called.

- Also modified tofino_sde_wrapper to return ERR_UNIMPLEMENTED
  if the HotplugPort method is called.

Signed-off-by: Derek G Foster <derek.foster@intel.com>

2022-11-01 19:36 UTC, 5abeel requested changes

2022-11-01 19:36 UTC, 5abeel commented on stratum/hal/lib/tdi/dpdk/BUILD
> +	":dpdk_port_config",
Not familiar enough with bazel, but is there a recommended way to sort these? either alphabetical or by starting chars `:` `//` `@`?

2022-11-01 19:36 UTC, 5abeel commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +namespace {
Do we need a named namespace? Assume this is not accessible or usable from other files/objects...

2022-11-01 19:36 UTC, 5abeel commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +  switch (config.cfg.port_type) {
Add check if `config` is null before accessing members like `config.cfg`

2022-11-01 19:36 UTC, 5abeel commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +  switch (config.cfg.port_type) {
Same comment as above

Add check if `config` is null before accessing members like `config.cfg`

2022-11-01 19:36 UTC, 5abeel commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +      if (status.ok()) {
A slight deviation of style with what rest of Stratum code (even though this works)

Rest of code uses a style:

```
if (status == ::util::OkStatus())
```

2022-11-01 20:41 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +  switch (config.cfg.port_type) {
Config is passed by reference. References can never be null.

2022-11-01 20:43 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +      if (status.ok()) {
I believe the preferred expression is `status.ok()`. The `ok` method is specifically provided so you can test for ok.
The `status == ::util::OkStatus()` is unnecessarily long and complicated.

2022-11-01 20:46 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +namespace {
Exactly. Anonymous namespaces allow you to declare functions with local scope only. This idiom is used in a number of other places in the code. It'd like defining a `static` function in C.

In fact, when I partitioned SdeWrapper and YangParseTreePaths, I had to extract most of the functions and put them in a named namespace so they _could_ be used by other files.

2022-11-01 21:26 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/BUILD
> +	":dpdk_port_config",
Not that I'm aware of. We can try running them through Bazelisk and see what it does. It it reeorders them, we can probably consider the output to be canonical.

2022-11-01 21:27 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +  switch (config.cfg.port_type) {
Same answer as above. References can never be null. That's one of the reasons I made it a reference. :)

2022-11-02 13:19 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +      if (status.ok()) {
I just grepped the code. I found 553 occurrences of `status.ok()` and one occurrence of `status == ::util::OkStatus()`. There is one other instance of `== ::util::OkStatus()`, but it's a special case.

2022-11-02 13:26 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/BUILD
> +	":dpdk_port_config",
Oops: `buildifier`, not `bazelisk`

2022-11-02 13:58 UTC, 5abeel commented on stratum/hal/lib/tdi/dpdk/dpdk_chassis_manager.cc
> +      if (status.ok()) {
ok thanks for checking

2022-11-02 13:58 UTC, 5abeel commented on stratum/hal/lib/tdi/dpdk/BUILD
> +	":dpdk_port_config",
We can take this on in the future if needed. No need to hold up this PR for a minor "nice-to-have" ordering

2022-11-02 13:58 UTC, 5abeel approved these changes
lgtm

2022-11-02 14:29 UTC, ffoulkes commented on stratum/hal/lib/tdi/dpdk/BUILD
> +	":dpdk_port_config",
I just tried Buildifier. It reordered some of the entries in the `deps` parameters, but it didn't move around any of the targets. It also told me that the `load` statements have a couple of unused imports we can delete.

I tend to order targets more or less alphabetically. I also tend to put tests at the bottom of file, though I think I also sometimes place them after the target they test.

2022-11-02 17:10 UTC, nupuruttarwar approved these changes
LGTM

2022-11-02 17:26 UTC, merged