Merge ES2K changes
ipdk-io/stratum-dev pull request #72
Opened 2023-04-27 17:57 UTC by ffoulkes

2023-04-27 21:33 UTC, nupuruttarwar requested changes

2023-04-27 21:33 UTC, nupuruttarwar commented on stratum/hal/bin/tdi/es2k/es2k_port_config.pb.txt
> +  platform: PLT_P4_IPU_ES2000
Please change this to E2100

2023-04-27 21:33 UTC, nupuruttarwar commented on stratum/hal/bin/tdi/es2k/es2k_skip_p4.conf
> +        "chip_family": "mev",
change mev to E2100

2023-04-27 21:33 UTC, nupuruttarwar commented on stratum/hal/lib/tdi/es2k/es2k_port_manager.cc
> +// need it since we don't add port for MEV
add port for E2100

2023-05-02 17:15 UTC, ffoulkes commented on stratum/hal/bin/tdi/es2k/es2k_port_config.pb.txt
> +  platform: PLT_P4_IPU_ES2000
This is an interface change. I think it's a mistake to change it at the last minute. I recommend leaving it as-is for the time being and developing a transition plan before we make the change.

2023-05-02 17:17 UTC, ffoulkes commented on stratum/hal/bin/tdi/es2k/es2k_skip_p4.conf
> +        "chip_family": "mev",
This is an interface change. Same as preceding comment.

2023-05-02 17:18 UTC, ffoulkes commented on stratum/hal/lib/tdi/es2k/es2k_port_manager.cc
> +// need it since we don't add port for MEV
We should actually just delete the comment.

2023-05-13 17:53 UTC, closed without merging